services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'mcncl/backstage-docs-syncer']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"

