steps:
  - label: "Lint"
    plugins:
      - docker-compose#v3.1.0:
          run: lint

  - label: "Test"
    plugins:
      - docker-compose#v3.1.0:
          run: test

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.1.2:
          files:
            - hooks/**
            - lib/**
