#!/bin/bash

function check_bucket_exists(){
    local BUCKET=$1

    if aws s3api head-bucket --bucket $BUCKET; then
        return 0
    else
        return 1
    fi
}

function check_mk_docs_file_exists(){
    if [[ $(find . -name "mkdocs.yml" | wc -l) -lt 1 ]]; then
        return 1
    else
        return 0
    fi
}