#!/bin/bash

function check_bucket_exists(){
    local BUCKET=$1

    if aws s3api head-bucket --bucket "$BUCKET"; then
        return 0
    else
        return 1
    fi
}

function check_mk_docs_file_exists(){
    if [ $(find . -name "mkdocs.yml") ]; then
        return 0
    else
        cat > mkdocs.yml<< EOF
site_name: Placeholder
site_description: This is a placeholder mkdocs.yml file.
EOF
        return 0
    fi
}